include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - prefer_final_fields
    - avoid_print
    - use_super_parameters
    - prefer_single_quotes

analyzer:
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'