import 'package:flutter_test/flutter_test.dart';
import 'package:shopping_app/utils/subscription_limits.dart';
void main() {
  test('SUB-01: 3 tiers', () => expect(SubscriptionTier.values.length, 3));
  test('SUB-02: free family group exist', () => expect(SubscriptionTier.values, containsAll([SubscriptionTier.free,SubscriptionTier.family,SubscriptionTier.group])));
  test('SUB-03: free maxOwnedSharedLists=3', () => expect(SubscriptionLimits.maxOwnedSharedLists(SubscriptionTier.free),3));
  test('SUB-04: family maxOwnedSharedLists=5', () => expect(SubscriptionLimits.maxOwnedSharedLists(SubscriptionTier.family),5));
  test('SUB-05: group maxOwnedSharedLists=10', () => expect(SubscriptionLimits.maxOwnedSharedLists(SubscriptionTier.group),10));
  test('SUB-06: maxOwnedSharedLists increases with tier', () { expect(SubscriptionLimits.maxOwnedSharedLists(SubscriptionTier.family),greaterThan(SubscriptionLimits.maxOwnedSharedLists(SubscriptionTier.free))); expect(SubscriptionLimits.maxOwnedSharedLists(SubscriptionTier.group),greaterThan(SubscriptionLimits.maxOwnedSharedLists(SubscriptionTier.family))); });
  test('SUB-07: free maxMembersPerList=5', () => expect(SubscriptionLimits.maxMembersPerList(SubscriptionTier.free),5));
  test('SUB-08: family maxMembersPerList=10', () => expect(SubscriptionLimits.maxMembersPerList(SubscriptionTier.family),10));
  test('SUB-09: group maxMembersPerList=25', () => expect(SubscriptionLimits.maxMembersPerList(SubscriptionTier.group),25));
  test('SUB-10: maxMembersPerList increases with tier', () { expect(SubscriptionLimits.maxMembersPerList(SubscriptionTier.family),greaterThan(SubscriptionLimits.maxMembersPerList(SubscriptionTier.free))); expect(SubscriptionLimits.maxMembersPerList(SubscriptionTier.group),greaterThan(SubscriptionLimits.maxMembersPerList(SubscriptionTier.family))); });
  test('SUB-11: free maxJoinedSharedLists=3', () => expect(SubscriptionLimits.maxJoinedSharedLists(SubscriptionTier.free),3));
  test('SUB-12: family maxJoinedSharedLists=5', () => expect(SubscriptionLimits.maxJoinedSharedLists(SubscriptionTier.family),5));
  test('SUB-13: group maxJoinedSharedLists=10', () => expect(SubscriptionLimits.maxJoinedSharedLists(SubscriptionTier.group),10));
  test('SUB-14: joined lists increases with tier', () { expect(SubscriptionLimits.maxJoinedSharedLists(SubscriptionTier.family),greaterThan(SubscriptionLimits.maxJoinedSharedLists(SubscriptionTier.free))); expect(SubscriptionLimits.maxJoinedSharedLists(SubscriptionTier.group),greaterThan(SubscriptionLimits.maxJoinedSharedLists(SubscriptionTier.family))); });
  test('SUB-15: fromString family', () => expect(SubscriptionLimits.fromString('family'),SubscriptionTier.family));
  test('SUB-16: fromString group', () => expect(SubscriptionLimits.fromString('group'),SubscriptionTier.group));
  test('SUB-17: fromString free', () => expect(SubscriptionLimits.fromString('free'),SubscriptionTier.free));
  test('SUB-18: fromString null -> free', () => expect(SubscriptionLimits.fromString(null),SubscriptionTier.free));
  test('SUB-19: fromString unknown -> free', () => expect(SubscriptionLimits.fromString('x'),SubscriptionTier.free));
  test('SUB-20: fromString empty -> free', () => expect(SubscriptionLimits.fromString(''),SubscriptionTier.free));
  test('SUB-21: tierToString free', () => expect(SubscriptionLimits.tierToString(SubscriptionTier.free),'free'));
  test('SUB-22: tierToString family', () => expect(SubscriptionLimits.tierToString(SubscriptionTier.family),'family'));
  test('SUB-23: tierToString group', () => expect(SubscriptionLimits.tierToString(SubscriptionTier.group),'group'));
  test('SUB-24: round-trip fromString(tierToString(x))==x', () { for(final t in SubscriptionTier.values){expect(SubscriptionLimits.fromString(SubscriptionLimits.tierToString(t)),t);} });
  test('SUB-25: tierDisplayName free', () => expect(SubscriptionLimits.tierDisplayName(SubscriptionTier.free),'Free Plan'));
  test('SUB-26: tierDisplayName family', () => expect(SubscriptionLimits.tierDisplayName(SubscriptionTier.family),'Family Plan'));
  test('SUB-27: tierDisplayName group', () => expect(SubscriptionLimits.tierDisplayName(SubscriptionTier.group),'Group Plan'));
  test('SUB-28: isHistoryUnlimited only for group', () { expect(SubscriptionLimits.isHistoryUnlimited(SubscriptionTier.group),isTrue); expect(SubscriptionLimits.isHistoryUnlimited(SubscriptionTier.free),isFalse); expect(SubscriptionLimits.isHistoryUnlimited(SubscriptionTier.family),isFalse); });
  test('SUB-29: free maxCategoriesPerItem=1', () => expect(SubscriptionLimits.maxCategoriesPerItem(SubscriptionTier.free), 1));
  test('SUB-30: family maxCategoriesPerItem=3', () => expect(SubscriptionLimits.maxCategoriesPerItem(SubscriptionTier.family), 3));
  test('SUB-31: group maxCategoriesPerItem=5', () => expect(SubscriptionLimits.maxCategoriesPerItem(SubscriptionTier.group), 5));
  test('SUB-32: maxCategoriesPerItem increases with tier', () { expect(SubscriptionLimits.maxCategoriesPerItem(SubscriptionTier.family), greaterThan(SubscriptionLimits.maxCategoriesPerItem(SubscriptionTier.free))); expect(SubscriptionLimits.maxCategoriesPerItem(SubscriptionTier.group), greaterThan(SubscriptionLimits.maxCategoriesPerItem(SubscriptionTier.family))); });
  test('SUB-33: supportsMultiCategory false for free', () => expect(SubscriptionLimits.supportsMultiCategory(SubscriptionTier.free), isFalse));
  test('SUB-34: supportsMultiCategory true for family', () => expect(SubscriptionLimits.supportsMultiCategory(SubscriptionTier.family), isTrue));
  test('SUB-35: supportsMultiCategory true for group', () => expect(SubscriptionLimits.supportsMultiCategory(SubscriptionTier.group), isTrue));
  test('SUB-36: free historyDays=30', () => expect(SubscriptionLimits.historyDays(SubscriptionTier.free), 30));
  test('SUB-37: family historyDays=90', () => expect(SubscriptionLimits.historyDays(SubscriptionTier.family), 90));
  test('SUB-38: group historyDays=-1 (unlimited)', () => expect(SubscriptionLimits.historyDays(SubscriptionTier.group), -1));
  test('SUB-39: historyDays increases free->family', () => expect(SubscriptionLimits.historyDays(SubscriptionTier.family), greaterThan(SubscriptionLimits.historyDays(SubscriptionTier.free))));
  test('SUB-40: tierBadgeLabel free=FREE', () => expect(SubscriptionLimits.tierBadgeLabel(SubscriptionTier.free), 'FREE'));
  test('SUB-41: tierBadgeLabel family=FAMILY', () => expect(SubscriptionLimits.tierBadgeLabel(SubscriptionTier.family), 'FAMILY'));
  test('SUB-42: tierBadgeLabel group=GROUP', () => expect(SubscriptionLimits.tierBadgeLabel(SubscriptionTier.group), 'GROUP'));
}
